MOUSEKEY_ENABLE = yes

RGBLIGHT_ENABLE = yes

MCU = RP2040
BOOTLOADER = rp2040

RGBLIGHT_ENABLE = yes      # or no
OLED_ENABLE = yes   # or no
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
LTO_ENABLE = yes

VELOCIKEY_ENABLE=yes
WPM_ENABLE = yes
WS2812_DRIVER = vendor